# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-02-11 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='credit_days',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='cut_days',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='cut_method',
            field=models.CharField(choices=[('sm', 'in')], default='sm', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='install_date',
            field=models.DateField(default=datetime.datetime(2016, 2, 11, 21, 6, 15, 460197, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='install_price',
            field=models.DecimalField(decimal_places=2, default=123.34, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='install_type',
            field=models.CharField(choices=[('in', 'in')], default='in', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='invoice_date',
            field=models.DateField(default=datetime.datetime(2016, 2, 11, 21, 6, 44, 308240, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='monthly_cuote',
            field=models.DecimalField(decimal_places=2, default=2343.44, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='monthly_type',
            field=models.CharField(choices=[('in', 'in')], default='dp', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='notificatios_method',
            field=models.CharField(choices=[('me', 'SMS y Email')], default='me', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='payment_method',
            field=models.CharField(choices=[('ot', 'ot')], default='ot', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 2, 11, 21, 8, 29, 492474, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
