# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_auto_20160211_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_type_plan', models.CharField(choices=[('dp', 'in')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='cut_method',
            field=models.CharField(choices=[('sm', 'Modulo SM')], max_length=2),
        ),
        migrations.AddField(
            model_name='service',
            name='additional',
            field=models.ManyToManyField(to='services.Additional'),
        ),
        migrations.AddField(
            model_name='service',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.Plan'),
            preserve_default=False,
        ),
    ]
