# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20170323_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='additional',
            field=models.ManyToManyField(to='services.Additional'),
        ),
    ]
