# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20170323_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='monthly_type_plan',
            field=models.CharField(choices=[('dp', 'Definida en planes')], max_length=2),
        ),
        migrations.AlterField(
            model_name='service',
            name='monthly_type',
            field=models.CharField(choices=[('dp', 'Definida en planes')], max_length=2),
        ),
    ]
