# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20170325_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='monthly_type_plan',
            field=models.CharField(choices=[('dp', 'Definida en planes')], default='dp', max_length=2),
        ),
        migrations.AlterField(
            model_name='service',
            name='additional',
            field=models.ManyToManyField(blank=True, null=True, to='services.Additional'),
        ),
        migrations.AlterField(
            model_name='service',
            name='credit_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='cut_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='cut_method',
            field=models.CharField(blank=True, choices=[('sm', 'Modulo SM')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='install_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='install_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='install_type',
            field=models.CharField(blank=True, choices=[('in', 'in')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='monthly_cuote',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='monthly_type',
            field=models.CharField(blank=True, choices=[('dp', 'Definida en planes')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='notificatios_method',
            field=models.CharField(choices=[('sm', 'SMS'), ('em', 'Email')], default='em', max_length=2),
        ),
        migrations.AlterField(
            model_name='service',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ot', 'otro'), ('tr', 'Transferencia'), ('de', 'Deposito'), ('ch', 'Cheque')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
