# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-14 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20170411_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='notificatios_method',
            field=models.CharField(choices=[('sm', 'SMS'), ('em', 'Email'), ('se', 'Email y SMS')], default='em', max_length=2),
        ),
    ]
