# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20170414_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='comments',
            field=models.TextField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='install_type',
            field=models.CharField(blank=True, choices=[('in', 'Inalambrica')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='mac',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='serial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='so',
            field=models.CharField(blank=True, choices=[('01', 'S.O 1'), ('02', 'S.O 2')], max_length=20, null=True),
        ),
    ]
