# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-14 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20170414_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
