# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-27 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_celda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='celdaAP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Celda'),
        ),
        migrations.AlterField(
            model_name='service',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Server'),
        ),
    ]
