# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20170427_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celda',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
