# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170205_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_registry',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
