# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170205_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ci',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('cp', 'Cliente potencial'), ('cr', 'Cliente Registrado'), ('no', 'Ninguno')], default='cp', max_length=2),
        ),
    ]
