# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170205_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bithdate',
            new_name='birthdate',
        ),
    ]
