# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170205_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ci',
            new_name='dni',
        ),
        migrations.AddField(
            model_name='user',
            name='type_dni',
            field=models.CharField(choices=[('E', 'Extranjero'), ('V', 'Venezolano'), ('J', 'RIF')], default='V', max_length=1),
            preserve_default=False,
        ),
    ]
