# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170313_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='series',
            field=models.IntegerField(blank=True, choices=[(1, 'Sin impuesto'), (2, 'Con impuesto')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_dni',
            field=models.CharField(blank=True, choices=[('E', 'Extranjero'), ('V', 'Venezolano'), ('J', 'RIF')], max_length=1, null=True),
        ),
    ]
