# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-13 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
