# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170511_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_people',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_people',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.ContactPeople'),
        ),
    ]
