# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-11 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20170511_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_people',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_people',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ContactPeople'),
        ),
    ]
