# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-13 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20170511_2237'),
        ('accounts', '0013_user_business_name'),
    ]

    operations = [
    ]
